steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/pawpal-artifact/pawpal-image:$COMMIT_SHA"
      - "."
  - name: gcr.io/cloud-builders/docker
    args:
      - "push"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/pawpal-artifact/pawpal-image:$COMMIT_SHA"
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "pawpal"
      - "--image=us-central1-docker.pkg.dev/$PROJECT_ID/pawpal-artifact/pawpal-image:$COMMIT_SHA"
      - "--region=us-central1"
      - "--cpu=1"
      - "--memory=2048Mi"
      - "--allow-unauthenticated"
      - "--set-secrets=GCS_BUCKET_NAME=gcs_bucket_name:latest, CREDENTIALS_PATH=credentials_path:latest"
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/pawpal-artifact/pawpal-image:$COMMIT_SHA"
logsBucket: "gs://pawpal-logs/logs"
